---
title: "My english activity log"
---

The message from teacher: From now on, you will use this article to include every single activity that you do in English in a chronological order (e.g. reading a book in English, watching TV shows and series in English, going to an English Evening in Mons, travelling to an English-speaking country, playing games in English such as the pretty exciting game LyricsTraining, etc.). You can even write a few lines about what you’ve watched/read/done and recommend certain things to your friends. The sky’s the limit! We value personal initiative and we will be happy to read whatever you have to offer.

So i will respect this mission , up to mow i have strarted to cummicate with people in a shop who speak english and seen video in VO on youtube about power of the cells, leaf and walkers protein.

The 4th of october I have send messages to foreign people whith who I communicate
THe weekend of the 5th and the 6th October , I have been working about the kingdom of Chromista and Animalia and I have search informations about the Kingdom of EuKaryota. I sarted to build a systematic classification of being. For that, I have consulted website like http://www.marinespecies.org/index.php or even http://nordicmicroalgae.org/galleries/norwegian-sea who are useful to class Animalia. I have used  https://www.algaebase.org/search/species/ too, because this website is interesting to have information of the Algae and being organism.
