---
title: "Article 5: Wing genes responsible for tiny treehopper's extraordinary helmet"
author: 
  - name: "Dylan Delporte"
date: "12-16-2019"
categories:
        - Mimicry of species
preview: image/cicadelle.jpg
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Vocabulary 

| Words from the text | Functions   |  Synonym/explanation in English |
| ------------------- | ------------|------------- |
| Treehopper | Noun | It's a bug living on trees and who has a thorn-shaped  |
| Helmet | Noun | A hard hat |
| To shed light | Verb | To explain  |
| The headgear | Noun | All things who can wear your head |
| The Kernel | Noun | A grain |
| Cozy | Adjective | Something comfortable |
| A mesh | Noun | A network |
| Rooftop | Noun | The surface of the roof |
| To feast | Verb | To make a good meal , To feed  |
| To blow | Verb | To impress |
| Indeed | Adverb | In fact ,to be sure  |
| The thorn | Noun | a spine of tree |
| To perch atop | Verb | To be on the peak of something|
| To borrow | Verb |  |
| To seek (sought,sought) | Verb | To resort |
| To tackle | Verb | To take something forward |
| Picky (informal) | Adjective | Fastidious |
| Painstaking | Adjective | To do with a great care |
| Smooth-surfaced | Adjective | Flat-surfaced |
| To wade | Verb | To move with difficulty through something |
|  |  |  |
|  |  |  |
|  |  |  |
|  |  |  |
|  |  |  |
|  |  |  |
|  |  |  |
|  |  |  |
|  |  |  |
|  |  |  |
|  |  |  |
|  |  |  |
|  |  |  |




## PDF
PDF of the article without pictures and with the vocabulary put in color: 

# Analysis table 

|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers          | Cera R. Fisher, Jill L. Wegrzyn, Elizabeth L. Jockusch from the University of Connecticut |
| Published in?               | 9 december 2019 |
| General topic?              |  |
| Procedure/what was examined? |  |
| Conclusions/discovery?       |  |
| Remaining questions?         |  |

# Bibliography 

## website 
https://www.sciencedaily.com/releases/2019/12/191209112152.htm 

consulted the 13 December 2019 at 2 PM and 28 minutes

## Pictures

All pictures are from google image

