---
title: "Article 6 : The giant squid genome holds surprises "
author: 
  - name: "Dylan Delporte"
date: "02-17-2020"
categories:
        - Mimicry of species
        - Müllerian mimicry
        - Mimicry of environment
preview: 
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Vocabulary 

| Words from the text | Functions   |  Synonym/explanation in English |
| ------------------- | ------------|------------- |
| Elusive | Adjective | To be difficult to reach| 
| Sporting  | Adjective | To be generous  | 
| Telltale | Adjetive | Indicating| 
| Ashore | Adverb | coming up to the sea | 
| To mesmerize | Verb | To hypnotize | 
| A Diorama | Noun | A model in three dimention | 
| To intrigue | Verb | to captive | 
| To arise from (arose, arose, arisen) | Verb  |To start to exist |
| To witness the event| Verb | To see the even | 
| To sketch | Verb | To draw, describe something | 
| Eclectic | Adjective | Wide |
| Slimy | Adjective | Like slime|
| To maroon| Verb | To be lost |
| A beak| Noun | A  piece of the anatomy used to break the food like for bird on the mouth|
| The realm | Noun  | A kingdom|
| The counterpart | Noun | Something with the same function than another thing |
| Squishy | Adjective| Soft |
| The mantle| Noun | The pallium, a piece ofthe anatomy of Mollusca able to create a exoskeleton or a endoskeleton to protect the visceral mass |
| To propel| Verb| To move forward or onward|
| A layer | Noun | It's relative to the endoskeleton in this article |
| To tip | Verb | | 
| emanate | | |
| A salami slicer | Noun | |
| To probe| Verb | |
| A handful | Noun| |
| To overlap| Verb | |
| Sufficiently | Adverb | |
| pending | Adjective | |
| Alas | | |
| To shatter| Verb | |
| A lump| Noun | |


## PDF
PDF of the article without pictures and with the vocabulary put in yellow:

<>

# species mentionned in the article (in red in the text )

## Phyllum of Mollusca, Class of Cephalopoda

### SubClass of the cuttlefishes



### SubClass of the octopuses

The two-spot octopus

### SubClass of The squids

The giant squid , _Architeudis dux_

_Mesonychoteuthis hamiltoni_

Pygmy squids

The clubhook squid

The humblock squid

The purpleback squid

### SubClass of The nautilusses

## Phyllum of the Mollusca, Class of Bivalva
The Pacific Oyster

## Phyllum of the Mollusca, Class of Gasteropoda
The giant owl limpet

## Another species

The sperm whale 

The eel 

The giant seal

# Analysis table 

|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers                  |     Ricky Lewis | 
|Bibliography of the researchers | <http://www.rickilewis.com/>  consulting the 17th of February 2020    |
| Published in?                | 10 February 2020 on the website "Technology.org" and the 6 February on the website "DNAscience"                                                  |
| General topic?               | The general topic is the giant squids genome | How they use their abilities  |
| Conclusions/discovery?       |   |
| Remaining questions?         | There are no remaining questions at the end of the article |

# Bibliography

## pictures

All pictures are from the article or google image

## website

<https://www.technology.org/2020/02/10/the-giant-squid-genome-holds-surprises/>
consulting the 15 February 2020 

<https://blogs.plos.org/dnascience/2020/02/06/the-giant-squid-genome-holds-surprises/>
consulting the 17 February 2020

<http://www.rickilewis.com/>
consulting the 17 February 2020


